# Generated by Django 3.2.4 on 2021-06-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_auto_20210514_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creada'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='portfolio', verbose_name='Seleccione imagen'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='inactiva', max_length=10, verbose_name='Estado'),
        ),
    ]
