# Generated by Django 3.2 on 2021-04-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('author', models.CharField(max_length=250, verbose_name='Autor')),
                ('image', models.ImageField(upload_to='img', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=10, verbose_name='Estado')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
