# Generated by Django 3.2 on 2021-04-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_alter_anuncio_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='author',
            field=models.CharField(max_length=150, null=True, verbose_name='Autor de la publicacion'),
        ),
    ]
