# Generated by Django 3.2 on 2021-04-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0006_alter_anuncio_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='author',
            field=models.CharField(default='', max_length=150, verbose_name='Autor de la publicacion'),
            preserve_default=False,
        ),
    ]
