# Generated by Django 3.2 on 2021-04-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0007_alter_anuncio_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='author',
        ),
    ]
