# Generated by Django 3.2 on 2021-04-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0013_alter_anuncio_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='texto',
            field=models.TextField(help_text='Enter field documentation', verbose_name='Contenido'),
        ),
    ]
