# Generated by Django 3.2 on 2021-04-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0016_alter_anuncio_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='texto',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='estado',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='anuncio',
            old_name='titulo',
            new_name='title',
        ),
    ]
