# Generated by Django 3.2 on 2021-04-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0017_auto_20210421_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='state',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=10, verbose_name='Estado'),
        ),
    ]
